---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: yolov5n
    serving.kserve.io/deploymentMode: ModelMesh
  name: rps
  labels:
    name: rps
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      runtime: model-server
      storage:
        key: aws-connection-my-storage
        path: models/yolov5n/yolov5n.onnx

